name: Build image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-image:
    runs-on: [self-hosted, large]
    steps:
      - name: Install aproxy
        run: sudo snap install aproxy --edge
      - name: Configure aproxy
        run: sudo snap set aproxy proxy=squid.internal:3128
      - name: Route all HTTP(S) traffic to aproxy
        run: >-
          sudo nft -f - << EOF
          define default-ip = $(ip route get $(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+') | grep -oP 'src \K\S+')
          define private-ips = { 10.0.0.0/8, 127.0.0.1/8, 172.16.0.0/12, 192.168.0.0/16 }
          table ip aproxy
          flush table ip aproxy
          table ip aproxy {
            chain prerouting {
              type nat hook prerouting priority dstnat; policy accept;
              ip daddr != \$private-ips tcp dport { 80, 443 } counter dnat to \$default-ip:8443
            }

            chain output {
              type nat hook output priority -100; policy accept;
              ip daddr != \$private-ips tcp dport { 80, 443 } counter dnat to \$default-ip:8443
            }
          }
          EOF
      - uses: canonical/setup-lxd@main
      - uses: actions/checkout@v4
      - name: Run build script
        run: bash build-image.sh
      - uses: actions/upload-artifact@v3
        with:
          name: self-hosted-runner-image 
          path: ./runner-image.tar.gz
          if-no-files-found: error
